codecov:
  bot: "shahzebsiddiqui"
  ci:
    - "travis.org"
  require_ci_to_pass: yes
  notify:
    after_n_builds: 1
    wait_for_ci: yes
coverage:
  precision: 2
  round: nearest
  range: 10...100
  status:
    project:
      default: yes
      target: auto
      threshold: null
      base: pr
      flags: null
      if_ci_failed: error
  notify:
    slack:
      url: "https://hooks.slack.com/services/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"
      threshold: 1%
      only_pulls: false
      branches: null
      flags: null
      paths: null
      paths: null