# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py

build:
  image: shahzebsiddiqui/readthedocs-docker-images:latest

formats: all

python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
