language: python
dist: xenial
arch:
  - amd64
git:
  quiet: true
branches:
  only:
    - devel
env:
  matrix:
    - LMOD_VERSION=6.6.2
addons:
  apt:
    packages:
      # install Lmod Deps
      - lua-filesystem
      - lua-json
      - lua-posix
      - lua-term
      - lua5.2
install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install -r docs/requirements.txt
  - source $TRAVIS_BUILD_DIR/src/buildtest/scripts/install_deps.sh $LMOD_VERSION
script:
  - type module
  - module --version
  - cd $TRAVIS_BUILD_DIR
  - source sourceme.sh
  - coverage run -m pytest tests/
  - coverage report -m
#  - coverage html
#  - export CODECOV_TOKEN="6469f129-1533-464e-a0a9-131466651231"
#  - bash <(curl -s https://codecov.io/bash)