language: python
dist: xenial
git:
  quiet: true
branches:
  only:
    - devel
env:
  matrix:
    - LMOD_VERSION=6.6.2
    - LMOD_VERSION=6.6.3

addons:
  apt:
    packages:
      # install Lmod Deps
      - lua-filesystem
      - lua-json
      - lua-posix
      - lua-term
      - lua5.2
install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install -r docs/requirements.txt
  - source $TRAVIS_BUILD_DIR/src/buildtest/scripts/install_deps.sh $LMOD_VERSION
script:
  - type module
  - module --version
  - cd $TRAVIS_BUILD_DIR
  - source sourceme.sh
  - buildtest --version