language: python
dist: xenial
arch:
  - amd64
git:
  quiet: true
branches:
  only:
    - devel
env:
  matrix:
    - LMOD_VERSION=6.6.2
addons:
  apt:
    packages:
      # install Lmod Deps
      - lua-filesystem
      - lua-json
      - lua-posix
      - lua-term
      - lua5.2
install:
  - pip --version
  - pip install --upgrade pip
  - pip --version
  - pip install -r docs/requirements.txt
  - source $TRAVIS_BUILD_DIR/src/buildtest/scripts/install_deps.sh
  - pip install easybuild
  - mkdir -p /opt/easybuild
  - export EASYBUILD_PREFIX=/opt/easybuild
  - eb --version
  - eb flex-2.6.3.eb --robot
  - module use $EASYBUILD_PREFIX
script:
  - type module
  - module --version
  - cd $TRAVIS_BUILD_DIR
  - source sourceme.sh
  - coverage run -m pytest tests/
  - coverage report -m

after_success:
  - bash <(curl -s https://codecov.io/bash)
