# path to buildtest-configs repo
BUILDTEST_CONFIGS_REPO:
# path to Tcl-buildtest-config repo
BUILDTEST_TCL_REPO:
# path to Ruby-buildtest-config repo
BUILDTEST_RUBY_REPO:
# path to R-buildtest-config repo
BUILDTEST_R_REPO:
# path to Python-buildtest-config repo
BUILDTEST_PYTHON_REPO:
# path to Perl-buildtest-config repo
BUILDTEST_PERL_REPO:
# List of all module trees
BUILDTEST_MODULE_ROOT:
# Module naming scheme
BUILDTEST_MODULE_NAMING_SCHEME: FNS
# path where to write buildtest logs
BUILDTEST_LOGDIR: /tmp/buildtest/logs
# path where to write buildtest tests
BUILDTEST_TESTDIR: /tmp/buildtest/tests
# Which shell to use when generating test
BUILDTEST_SHELL: sh
# Job Integration with buildtest
BUILDTEST_ENABLE_JOB: False
# job template for creating job scripts to be run with scheduler
BUILDTEST_JOB_TEMPLATE: template/job.slurm
# Remove test directory before writing test
BUILDTEST_CLEAN_BUILD: False
# Easybuild Integration
BUILDTEST_EASYBUILD: False
# OpenHPC Integration
BUILDTEST_OHPC: False
