BUILDTEST_MODULE_NAMING_SCHEME: FNS
BUILDTEST_EBROOT:
    - /nfs/grid/software/easybuild/IvyBridge/redhat/7.3
    - /nfs/grid/software/easybuild/Haswell/redhat/7.3
    - /nfs/grid/software/RHEL7/easybuild

BUILDTEST_CONFIGS_REPO: /lustre/workspace/home/siddis14/buildtest-configs
BUILDTEST_EASYCONFIG_REPO: /lustre/workspace/home/siddis14/easybuild-easyconfigs/easybuild/easyconfigs
BUILDTEST_TCL_REPO: /lustre/workspace/home/siddis14/Tcl-buildtest-config
BUILDTEST_RUBY_REPO: /lustre/workspace/home/siddis14/Ruby-buildtest-config
BUILDTEST_R_REPO: /lustre/workspace/home/siddis14/R-buildtest-config
BUILDTEST_PYTHON_REPO: /lustre/workspace/home/siddis14/Python-buildtest-config
BUILDTEST_PERL_REPO: /lustre/workspace/home/siddis14/Perl-buildtest-config
