# easybuild integration. Valid Options: [True, False]
BUILDTEST_EASYBUILD: False

# Delete Build Directory before writing tests.  Valid Options: [True, False]
BUILDTEST_CLEAN_BUILD: False

# OpenHPC integration. Valid options: [True, False]
BUILDTEST_OHPC: False

# binary test support. Valid options [True, False]
BUILDTEST_BINARY: False

# Configure shell when running test. Valid options [bash, csh, sh]. Default: [sh]
BUILDTEST_SHELL: sh

# list root of module tree where modules are installed. Specify multiple module tree as a list
BUILDTEST_MODULE_ROOT: []

# criteria for success threshold when running job. Valid Option: [0.0-1.0]    
BUILDTEST_SUCCESS_THRESHOLD: 1.0

# root of buildtest-configs repo
BUILDTEST_CONFIGS_REPO:

# directory where buildtest logs will be written. 
BUILDTEST_LOGDIR: /tmp/buildtest/logs

# directory where test scripts will be generated
BUILDTEST_TESTDIR: /tmp/buildtest/tests

# directory where buildtest will write .run files
BUILDTEST_RUN_DIR: /tmp/buildtest/run
