BUILDTEST_BINARY: true
BUILDTEST_CLEAN_BUILD: false
BUILDTEST_EASYBUILD: false
BUILDTEST_LOGDIR: $HOME/buildtest
BUILDTEST_MODULE_ROOT:
- /usr/share/lmod/lmod/modulefiles/Core
- /nfs/grid/software/moduledomains
BUILDTEST_OHPC: false
BUILDTEST_RUN_DIR: /tmp/buildtest
BUILDTEST_SHELL: sh
BUILDTEST_SUCCESS_THRESHOLD: 1.0
BUILDTEST_TESTDIR: $HOME/buildtest
