# list root of module tree where modules are installed. Specify multiple module tree as a list
BUILDTEST_MODULEPATH: []

# editor of choice when viewing files
# valid options: vim, emacs, nano
EDITOR: vim

build:
  # directory where test scripts will be generated
  testdir: $HOME/.buildtest/testdir

  module:
    # purge modules at start of each script
    purge:
      # set force: True to purge sticky modules (module --force purge)
      force: False